graph:
    resource: "@GraphBundle/Controller/"
    type:     annotation
    prefix:   /graph



account:
    resource: "@AccountBundle/Resources/config/routing.php"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation
